server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: polaris-tx-group #事务组名称 必须一定和你服务端配置的一样 必须 必须 必须
    nacos:
      discovery:
        server-addr: localhost:8848
        group: SEATA_GROUP
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# seata配置
seata:
  service:
    vgroup-mapping:
      polaris-tx-group: GZ
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace:
      group: SEATA_GROUP
      cluster: default
      username: nacos
      password: nacos
      application: seata-server

  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace:
      group: SEATA_GROUP
      username: nacos
      password: nacos



feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 1500
        readTimeout: 1500
logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml